// Course Constants

export const COURSE_CONSTANTS = {
    COURSE: {
        DEFAULT_PAGE: 1 as const,
        DEFAULT_LIMIT: 12 as const,
        DEFAULT_SORT: "createdAt" as const,
        DEFAULT_ORDER: "desc" as const,
        DEFAULT_VALUE: "" as const,
        CATEGORIES_MAX_LENGTH: 3 as const,
        PREDEFINED_CATEGORIES: [
            "Computer Science",
            "Mathematics",
            "Calculus",
            "Physics",
            "Linear Algebra",
            "Statistics",
            "Machine Learning",
            "Data Structures",
            "Algorithms",
            "Software Engineering",
            "Web Development",
            "Operating Systems",
            "Database",
            "Artificial Intelligence",
            "Networking",
            "Security",
            "Computer Architecture",
            "Computer System",
            "Hardware",
            "Computer Organization",
            "Programming Languages",
        ],
    },
    USER_COURSE: {
        DEFAULT_PAGE: 1 as const,
        DEFAULT_LIMIT: 10 as const,
        DEFAULT_SORT: "completedDate" as const,
        DEFAULT_ORDER: "desc" as const,
        MAXIMUM_TRACKED_COURSES: 3 as const,
    },
    RECORDING: {
        PREDEFINED_RECORD_TYPES: [
            "LECTURE",
            "DISCUSSION",
            "RECITATION",
            "QUIZ",
            "ASSIGNMENT",
            "HOMEWORK",
            "LAB",
            "PROJECT",
            "OTHER",
        ],
    },
};
